title: "Pide Lun"
author: "Pide Lun"
description: "University of Adelaide"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
minimal: true
mathjax: true

# layout

show_social: true
show_excerpts: false
show_frame: true
show_sidebar: false

# Menu

navigation:
  - {title: CV, file: "lunpide.pdf"}
  - {title: Research, file: "research.md"}
  - {title: Teaching, file: "teaching.md"}
  
   
 
 #{title: Feed, icon: rss, url: "/feed.xml"}

remote_theme: niklasbuschmann/contrast

plugins:
 - jekyll-remote-theme
 - jekyll-feed
