title: "Pide Lun"
author: "Pide Lun"
description: "University of Adelaide"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
minimal: true
mathjax: true

# layout

show_social: true
show_excerpts: false
show_frame: true
show_sidebar: false

# Menu

navigation:
  - {title: CV, file: "lunpide.pdf"}
  - {title: Research, url: "research.xtml"}
  - {title: Teaching, url: "https://github.com/researchecon/lunpide/blob/636b981666974725df280b6084e1fe4c264f8443/teaching.html"}
 
 #{title: Feed, icon: rss, url: "/feed.xml"}

remote_theme: niklasbuschmann/contrast

plugins:
 - jekyll-remote-theme
 - jekyll-feed
