title: "Pide Lun"
author: "Pide Lun"
description: "University of Adelaide"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
minimal: true
mathjax: true

# layout

show_social: true
show_excerpts: false
show_frame: true
show_sidebar: false

# Menu

navigation:
  - {title: CV, url: "https://github.com/researchecon/lunpide/blob/7d9058886b9deaf6c489a2df385abbb1b311b48c/lunpide.pdf"}
  - {title: Research, url: "/research.xml"}
  - {title: Teaching, url: "/teaching.xml"}
 
 #{title: Feed, icon: rss, url: "/feed.xml"}

remote_theme: niklasbuschmann/contrast

plugins:
 - jekyll-remote-theme
 - jekyll-feed
